### ISSUE TITLE
 Cannot call method 'authenticate' of null

### ISSUE THREAD

**Issue by Siafu** [einfallstoll/express-ntlm#10] opened 2015-06-12 15:26 UTC
I get this following error, no clue why. My code is as follows:
```
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var favicon = require('serve-favicon');
var logger = require('morgan');
var port = process.env.PORT || 8001;
var four0four = require('./utils/404')();
var ntlm = require('express-ntlm');

var environment = process.env.NODE_ENV;
app.use(favicon(__dirname + '/favicon.ico'));
app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());
app.use(logger('dev'));
app.use(ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    domain: 'ABC',
    domaincontroller: 'ldap://ABC.ds.corp',
}));

app.all('*', function(req, res) {
    console.log(JSON.stringify(req.ntlm));
});

app.use('/api', require('./routes'));
```

**Comment by einfallstoll** [comment] 2015-06-12 15:42
I saw this error before, but was not able to reproduce it again.

It seems like the module can't get a proxy for the provided connection id. This could be due to a different connection creating an HTTP request.

What browser in which version do you use? What version of node.js? And what version of `express-ntlm`?

**Comment by Siafu** [comment] 2015-06-12 15:48
Thank you for the quick response.
chrome: 43.0.2357.124 m, 
node: v0.10.36
express: 2.1.4

**Comment by Siafu** [comment] 2015-06-12 15:49
Also says No Authorization header present

**Comment by einfallstoll** [comment] 2015-06-12 15:52
I will have a look at it as soon as possible. Could you update to a more recent version of node e.g. 0.10.38 or 0.12.4?

**Comment by Siafu** [comment] 2015-06-12 15:55
i'll try

**Comment by Siafu** [comment] 2015-06-12 17:00
Updated to 0.12.4 same error.

**Comment by einfallstoll** [comment] 2015-06-12 17:04
Ok. I'll try to find the error as soon as possible. I'm setting up a new development environment, which could take a few days. Don't worry if I'm a little bit busy for a moment.

**Comment by einfallstoll** [comment] 2015-07-06 05:35
HI @Siafu, thanks for your patience. I'm working right now on resolving the issue, but I was not able to reproduce it.

The code I tested was the following:

````
var express = require('express'),
    ntlm = require('./lib/express-ntlm');

var app = express();

app.use(ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    domaincontroller: 'ldap://some.dc.com',
}));

app.all('*', function(request, response) {
    response.end(JSON.stringify(request.ntlm));
});

app.listen(80);
````

* What OS are you running on the server-side?
* What OS are you running on the client-side?

Could you try to add the following line to `node_modules/express-ntlm/lib/express-ntlm.js` on line 169 right before `proxy.authenticate` and post the output of this specific line after testing with 1-2 different browsers:

````
console.log(request.connection.id, Object.keys(cache._cache));
````

**Comment by Shpiller** [comment] 2015-07-22 08:34
I get this error too!
TypeError: Cannot read property 'authenticate' of null
at handle_type3 (/home/alexey/work/webcontrol/node_modules/express-ntlm/lib/express-ntlm.js:176:14)

It's happend when connect through nginx proxy server.
But if you connect directly to the port of node  there is no error.

 a new uid  creates in this line always
if (!request.connection.id) {
            request.connection.id = utils.uuidv4();
        }

my nginx config
server {
        listen 80 default_server;
        listen [::]:80 default_server;

       root /path/to/my/project/dir/;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://127.0.0.1:3000/;
                proxy_redirect off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                #proxy_redirect off;
                #proxy_set_header   X-Forwarded-Proto $scheme;
                #proxy_cache one;
                #proxy_cache_key sfs$request_uri$scheme;
        }

        location ~ ^/(css/|i/|js/|vendor/|favicon.ico) {
                root /home/alexey/work/webcontrol/public/;
                access_log off;
                expires 1h;
        }
}

**Comment by elawad** [comment] 2015-08-30 14:53
Same issue here. Occurs when using browser-sync, which uses a proxy server.

Using proxy server (browser-sync):
```
d210be03-b909-42f9-96a9-c2b69084fd84 [ 'b99f0419-6264-4258-849d-0cca33ac0e52' ]
```

Without proxy, running express app normally:
```
ad8f4156-040a-4d36-b2be-8c889f7ae43a [ 'ad8f4156-040a-4d36-b2be-8c889f7ae43a' ]
```

**Comment by einfallstoll** [comment] 2015-08-30 16:18
@elawad Thank you. I think I found the problem:

NTLM authenticates connections. If your browser opens different connections the authentication fails, because the module lost track of how far the authentication already is.

In an early version I tried using sessions which would have solved this problem but violated the protocol and had issues with Internet Explorer which rotates two or more connections by default.

The solution should be relatively easy now. I try to create a quick fix and if it works it should be possible to fix this issue today or tomorrow.

**Comment by einfallstoll** [comment] 2015-08-30 16:34
I don't have my test environment anymore and I can't reproduce the issue, so please add this

```
response.setHeader('Connection', 'keep-alive');
```

to the file [lib/express-ntlm.js on line 196](https://github.com/einfallstoll/express-ntlm/blob/master/lib/express-ntlm.js#L196), so that it looks like this:

```
    return function(request, response, next) {
        if (!request.connection.id) {
            request.connection.id = utils.uuidv4();
        }

        response.setHeader('Connection', 'keep-alive');

        var auth_headers = request.headers.authorization;
```

Let me know if this does the trick. Then I'll release a new version asap.

**Comment by elawad** [comment] 2015-08-30 18:34
@einfallstoll Thanks for the quick response. 
I've set the header, as you mentioned. But unfortunately the same error occurs.

**Comment by einfallstoll** [comment] 2015-08-31 06:41
@elawad That's not cool. May I know how you implemented `browser-sync`? It could be a problem with the configuration of `browser-sync`.

**Comment by elawad** [comment] 2015-09-01 05:39
Here's a stripped-down version of what I used to get the error. 
Run node app, then gulp in a separate process.

The express app on http://localhost:3000/ works fine. 
But browser-sync needs to start on a separate port. 
It uses http://localhost:4000/ and that causes the error.

**app.js**
````
'use strict';
var express = require('express');
var app = express();
var http = require('http');
var ntlm = require('express-ntlm');

app.use(ntlm({
	domain: 'xyz',
	domaincontroller: 'ldap://ldap.xyz.com'	
}));

app.get('/', function(req, res) {
	res.json(req.ntlm);
});

http.createServer(app).listen(3000, function () {
	console.log('app on 3000');
});
````

**gulpfile.js**
````
var gulp = require('gulp');
var browserSync	= require('browser-sync');

gulp.task('default', function () {
	browserSync.init({
		files: ['public/**/*.*'],
		proxy: 'http://localhost:3000',
		port: 4000,
		//browser: 'google chrome'
	});
});
````

**Comment by einfallstoll** [comment] 2015-09-01 06:37
It might help to add the header yourself:

```
proxy: {
    target: "localhost:8000",
    reqHeaders: function (config) {
        return {
            "host": config.urlObj.host,
            "accept-encoding": "identity",
            "agent": false,
            "connection": "keep-alive"
        }
    }
}
```

These header are passed through `foxy` to `http-proxy`.

**Comment by elawad** [comment] 2015-09-01 12:52
I added the proxy settings along with the reqHeader object to browser-sync. 
Still the same issue :/

Here's the response I received:
````
{ 'x-powered-by': 'Express',
  'www-authenticate': 'NTLM',
  date: 'Tue, 01 Sep 2015 12:39:46 GMT',
  connection: 'close',
  'transfer-encoding': 'chunked'
}
{ 'x-powered-by': 'Express',
  'www-authenticate': 'NTLM TlRMTVNTUAACAAAADAAMADgAAAAFgomiP+YHc1VyIzwAAAAAAAAAAJgAmABEAAAABgGxHQAA
AA9UAFUAUgBOAEUAUgACAAwAVABVAFIATgBFAFIAAQAWAEEAVABMAFYAVABCAFMARABDADAAMQAEABQAdAB1AHIAbgBlAHIALgBj
AG8AbQADACwAQQBUAEwAVgBUAEIAUwBEAEMAMAAxAC4AdAB1AHIAbgBlAHIALgBjAG8AbQAFABIAYwByAHAAYQBkAC4AYwBvAG0A
BwAIAC7SnEiz5NABAAAAAA==',
  date: 'Tue, 01 Sep 2015 12:39:46 GMT',
  connection: 'close',
  'transfer-encoding': 'chunked'
} 
{ 'x-powered-by': 'Express',
  'x-content-type-options': 'nosniff',
  'content-type': 'text/html; charset=utf-8',
  date: 'Tue, 01 Sep 2015 12:39:46 GMT',
  connection: 'close'
}
````

**Comment by einfallstoll** [comment] 2015-09-01 12:58
The first response is the answer to your intial request. The second one is the so-called challenge and in the third one there should be the final and successful answer.

Did you try to combine both suggestions? :arrow_right: Setting `connection` to `keep-alive` in both modules.

**Comment by elawad** [comment] 2015-09-01 13:04
I'm a bit unclear to your suggestion... where should the settings be add in both modules? 
I only added it to browser-sync. I don't have http-proxy nor foxy.

**Comment by einfallstoll** [comment] 2015-09-01 13:10
I see, it's a little bit misleading. `foxy` is dependency of `browser-sync` and `http-proxy` is a dependency of `foxy`. The `reqHeaders` I suggested to add will get passed through `browser-sync` to `foxy` and then to `http-proxy`, which means if you set this setting once, every module in this dependency-chain will receive it.

Now I'd like to know wether you added both `reqHeaders` to `browser-sync` **and** `response.setHeader('Connection', 'keep-alive');` to `express-ntlm` or if you removed my original suggestion after it didn't work and just used `reqHeaders` alone?

*(I hope you understand what I mean, because I fear that my explanation is f*** up)*

**Comment by elawad** [comment] 2015-09-01 13:57
OK I understood you now, thank you.
Yes I have both reqHeader in browser-sync, and response.setHeader in express-ntlm on line 196.

**Comment by elawad** [comment] 2015-09-01 14:34
Sorry, I should've mentioned: after adding the line to express-ntlm, I now receive this response from browser-sync, but still the same 'authenticate' error.

````
{ 'x-powered-by': 'Express',
  connection: 'keep-alive',
  'www-authenticate': 'NTLM',
  date: 'Tue, 01 Sep 2015 14:31:39 GMT',
  'transfer-encoding': 'chunked'
}
{ 'x-powered-by': 'Express',
  connection: 'keep-alive',
  'www-authenticate': 'NTLM TlRMTVNTUAACAAAADAAMADgAAAAFgomipAn3kIJkT20AAAAAAAAAAJQAlABEAAAABgGxHQAA
AA9UAFUAUgBOAEUAUgACAAwAVABVAFIATgBFAFIAAQAUAEEAVABMAFQAQgBTAEQAQwAwADQABAAUAHQAdQByAG4AZQByAC4AYwBv
AG0AAwAqAEEAVABMAFQAQgBTAEQAQwAwADQALgB0AHUAcgBuAGUAcgAuAGMAbwBtAAUAEgBjAHIAcABhAGQALgBjAG8AbQAHAAgA
WTzX6cLk0AEAAAAA',
  date: 'Tue, 01 Sep 2015 14:31:39 GMT',
  'transfer-encoding': 'chunked'
}
{ 'x-powered-by': 'Express',
  connection: 'keep-alive',
  'x-content-type-options': 'nosniff',
  'content-type': 'text/html; charset=utf-8',
  date: 'Tue, 01 Sep 2015 14:31:39 GMT'
}
{ 'x-powered-by': 'Express',
  connection: 'keep-alive',
  'www-authenticate': 'NTLM',
  date: 'Tue, 01 Sep 2015 14:31:39 GMT',
  'transfer-encoding': 'chunked'
}
{ 'x-powered-by': 'Express',
  connection: 'keep-alive',
  'www-authenticate': 'NTLM TlRMTVNTUAACAAAADAAMADgAAAAFgomirhzqTLbyFaIAAAAAAAAAAJQAlABEAAAABgGxHQAA
AA9UAFUAUgBOAEUAUgACAAwAVABVAFIATgBFAFIAAQAUAEEAVABMAFQAQgBTAEQAQwAwADQABAAUAHQAdQByAG4AZQByAC4AYwBv
AG0AAwAqAEEAVABMAFQAQgBTAEQAQwAwADQALgB0AHUAcgBuAGUAcgAuAGMAbwBtAAUAEgBjAHIAcABhAGQALgBjAG8AbQAHAAgA
UdgG6sLk0AEAAAAA',
  date: 'Tue, 01 Sep 2015 14:31:39 GMT',
  'transfer-encoding': 'chunked'
}
{ 'x-powered-by': 'Express',
  connection: 'keep-alive',
  'x-content-type-options': 'nosniff',
  'content-type': 'text/html; charset=utf-8',
  date: 'Tue, 01 Sep 2015 14:31:39 GMT'
}
````

**Comment by einfallstoll** [comment] 2015-09-02 06:54
There's something strange going on. Could you log the HTTP headers from the request as they arrive on the server?

It should be as easy as add this line

```
console.log('Request HTTP Headers:', request.headers);
```

to the file [lib/express-ntlm.js on line 196](https://github.com/einfallstoll/express-ntlm/blob/master/lib/express-ntlm.js#L196), so that it looks like this:

```
    return function(request, response, next) {
        if (!request.connection.id) {
            request.connection.id = utils.uuidv4();
        }

        console.log('Request HTTP Headers:', request.headers);
        response.setHeader('Connection', 'keep-alive');

        var auth_headers = request.headers.authorization;
```

**Comment by elawad** [comment] 2015-09-02 23:00
Here are my response headers. I noticed all the connections are closed.
````
Request HTTP Headers: { host: 'localhost:3000', connection: 'close' }

Request HTTP Headers: { 'accept-language': 'en-US,en;q=0.8,ar;q=0.6',
  'accept-encoding': 'identity',
  'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
  'upgrade-insecure-requests': '1',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  connection: 'close',
  host: 'localhost:3000',
  agent: 'false' }

Request HTTP Headers: { 'accept-language': 'en-US,en;q=0.8,ar;q=0.6',
  'accept-encoding': 'identity',
  'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
  'upgrade-insecure-requests': '1',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  authorization: 'NTLM TlRMTVNTUAABAAAAB7IIogYABgAxAAAACQAJACgAAAAGAbEdAAAAD1RCUy1BWU1FTlRVUk5FUg==',
  connection: 'close',
  host: 'localhost:3000',
  agent: 'false' }

Request HTTP Headers: { 'accept-language': 'en-US,en;q=0.8,ar;q=0.6',
  'accept-encoding': 'identity',
  'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
  'upgrade-insecure-requests': '1',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  authorization: 'NTLM TlRMTVNTUAADAAAAGAAYAIQAAABCAUIBnAAAAAwADABYAAAADgAOAGQAAAASABIAcgAAAAAAAADeAQAABYKIogYBsR0AAAAPEpLjqHYDESaJAS2vj8QPS1QAVQBSAE4ARQBSAGEAZQBsAGEAdwBhAGQAVABCAFMALQBBAFkATQBFAE4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnyyB3XDg3ZnFJVzMyyulwEBAAAAAAAAzyZ/eNLl0AHqNUUSMmyzkgAAAAACAAwAVABVAFIATgBFAFIAAQAUAEEAVABMAFQAQgBTAEQAQwAwADQABAAUAHQAdQByAG4AZQByAC4AYwBvAG0AAwAqAEEAVABMAFQAQgBTAEQAQwAwADQALgB0AHUAcgBuAGUAcgAuAGMAbwBtAAUAEgBjAHIAcABhAGQALgBjAG8AbQAHAAgAzyZ/eNLl0AEGAAQAAgAAAAgAMAAwAAAAAAAAAAAAAAAAMAAAEm/GSsC8z9kVwbuTnTiOsPXLXi0Z6HVTedq/4tYV2oYKABAAAAAAAAAAAAAAAAAAAAAAAAkAJgBIAFQAVABQAC8AbABvAGMAYQBsAGgAbwBzAHQAOgA0ADAAMAAwAAAAAAAAAAAAAAAAAA==',
  connection: 'close',
  host: 'localhost:3000',
  agent: 'false' }
 
TypeError: Cannot read property 'authenticate' of null
    at handle_type3 (\node_modules\express-ntlm\lib\express-ntlm.js:169:14)
    at \node_modules\express-ntlm\lib\express-ntlm.js:253:24
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (\node_modules\express\lib\router\index.js:312:13)
    at \node_modules\express\lib\router\index.js:280:7
    at Function.process_params (\node_modules\express\lib\router\index.js:330:12)
    at next (\node_modules\express\lib\router\index.js:271:10)
    at expressInit (\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (\node_modules\express\lib\router\index.js:312:13)

Request HTTP Headers: { 'accept-language': 'en-US,en;q=0.8,ar;q=0.6',
  'accept-encoding': 'identity',
  referer: 'http://localhost:4000/',
  accept: '*/*',
  'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
  connection: 'close',
  host: 'localhost:3000',
  agent: 'false' }

Request HTTP Headers: { 'accept-language': 'en-US,en;q=0.8,ar;q=0.6',
  'accept-encoding': 'identity',
  referer: 'http://localhost:4000/',
  accept: '*/*',
  'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
  authorization: 'NTLM TlRMTVNTUAABAAAAB7IIogYABgAxAAAACQAJACgAAAAGAbEdAAAAD1RCUy1BWU1FTlRVUk5FUg==',
  connection: 'close',
  host: 'localhost:3000',
  agent: 'false' }

Request HTTP Headers: { 'accept-language': 'en-US,en;q=0.8,ar;q=0.6',
  'accept-encoding': 'identity',
  referer: 'http://localhost:4000/',
  accept: '*/*',
  'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
  authorization: 'NTLM TlRMTVNTUAADAAAAGAAYAIQAAABCAUIBnAAAAAwADABYAAAADgAOAGQAAAASABIAcgAAAAAAAADeAQAABYKIogYBsR0AAAAPZxskzkuYrv3N7B81l2DFwFQAVQBSAE4ARQBSAGEAZQBsAGEAdwBhAGQAVABCAFMALQBBAFkATQBFAE4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzVKfdy76EbuD4BIJmT+wwgEBAAAAAAAAj1PLeNLl0AESFLdGXONp4AAAAAACAAwAVABVAFIATgBFAFIAAQAUAEEAVABMAFQAQgBTAEQAQwAwADQABAAUAHQAdQByAG4AZQByAC4AYwBvAG0AAwAqAEEAVABMAFQAQgBTAEQAQwAwADQALgB0AHUAcgBuAGUAcgAuAGMAbwBtAAUAEgBjAHIAcABhAGQALgBjAG8AbQAHAAgAj1PLeNLl0AEGAAQAAgAAAAgAMAAwAAAAAAAAAAAAAAAAMAAAEm/GSsC8z9kVwbuTnTiOsPXLXi0Z6HVTedq/4tYV2oYKABAAAAAAAAAAAAAAAAAAAAAAAAkAJgBIAFQAVABQAC8AbABvAGMAYQBsAGgAbwBzAHQAOgA0ADAAMAAwAAAAAAAAAAAAAAAAAA==',
  connection: 'close',
  host: 'localhost:3000',
  agent: 'false' }

TypeError: Cannot read property 'authenticate' of null
    at handle_type3 (\node_modules\express-ntlm\lib\express-ntlm.js:169:14)
    at \node_modules\express-ntlm\lib\express-ntlm.js:253:24
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (\node_modules\express\lib\router\index.js:312:13)
    at \node_modules\express\lib\router\index.js:280:7
    at Function.process_params (\node_modules\express\lib\router\index.js:330:12)
    at next (\node_modules\express\lib\router\index.js:271:10)
    at expressInit (\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (\node_modules\express\lib\router\index.js:312:13)
````

**Comment by einfallstoll** [comment] 2015-09-08 11:07
I honestly don't have a clue what could create this error. I really believe that's a behaviour within `browser-sync` or one of its dependencies and I can't reproduce it since I don't have an ADS anymore.

**Comment by Siafu** [comment] 2015-09-08 16:50
It's OK thanks for the help.

**Comment by elawad** [comment] 2015-09-09 22:39
@einfallstoll No worries, thanks for troubleshooting it. 
I ended up not using BrowserSync for the time being.

**Closed** 2015-09-10 16:52 UTC
Labels: bug

**Comment by mrjeremy28** [comment] 2016-03-25 15:11
not sure if anyone is still getting this error, but I am using nginx with reverse proxy and would randmonly get this error.
On my express-ntlm.js file on line 243:
if (ntlm_version === 3) {
    if (typeof cache.get_proxy(request.connection.id !== 'undefined') {
   /// more code here that i didn't touch
    }
}

i changed to:
if (ntlm_version === 3) {
    if (typeof cache.get_proxy(request.connection.id !== 'undefined' && typeof cache.get_proxy(request.connection.id !== null) {
   /// more code here that i didn't touch
    }
}
