### ISSUE TITLE
Incorrect user returned - race condition?

### ISSUE THREAD

**Issue by jamesbillinger** [einfallstoll/express-ntlm#17] opened 2016-05-05 11:37 UTC
We started deploying this on an internal website to a pool of 50 or so test users.  Twice now I've had a user come to me and show me that they were actually logged in as a different user.  If I have them logout, NTLM automatically logs them back in as their correct user.

I don't see how the browser could be sending someone else's credentials - especially given that a logout/login sends the correct ones.  So I have to assume that this is some kind of a race condition.  Is there a unique session built with the AD server for each authentication request?  Would a race condition be possible?

I have what I assume to be a pretty standard configuration - nginx proxy in front of a node.js server.  We do use an ldap load balancer in front of our DC's.  We've never had an issue with the LB, but I could take it out of the loop for testing if need be.

`express-ntlm@2.1.4`

```
 app.get('/login', ntlm({
    debug: function() {
      var args = Array.prototype.slice.apply(arguments);
      log('<auth>', args);
    },
    forbidden: function(req, res, next) {
      next();
    },
    internalservererror: function(req, res, next) {
      next();
    },
    badrequest: function(req, res, next) {
      next();
    },
    domain: 'HMC_DM',
    domaincontroller: 'ldap://ldap.haysmed.com'
  }), routes.views.auth.login);
```

By the way, extremely grateful for the middleware - this will make our users very happy (if we can get it working).  Thanks

**Comment by einfallstoll** [comment] 2016-05-13 09:33
I believe the problem *is* a race condition occurring because of [the way I identify connections](https://github.com/einfallstoll/express-ntlm/blob/master/lib/express-ntlm.js#L194). It could be possible, that node.js (or even your operating system) messes around with the connection and reuses the same connection twice or more resulting in mistakenly authenticated users. (Even though I'm [not the only one generating connection ids](http://stackoverflow.com/questions/6805432/how-to-uniquely-identify-a-socket-with-node-js).)

I don't have a testing environment at the moment, since I left the company I built this for, but I'd appreciate any Pull Request if you're able to fix the issue.

**Comment by Warun26** [comment] 2016-09-11 16:11
I am using express-ntlm for an internal website as well. There have been many instances where users have complained that they are logged in as a different user. Is there a fix for this bug available?

**Comment by einfallstoll** [comment] 2016-09-11 16:55
@Warun26: I've never been able to successfully reproduce the issue in a development environment, although I saw it occasionally occur in production. It's extremely hard to debug the issue, as I have no idea where the error could be. And it might also be possible it's caused by something else such as node.js or the operating system itself.

**Comment by einfallstoll** [comment] 2016-10-11 06:04
Proxies in front of the application break the NTLM authentication. See #20 for more details.

**Closed by einfallstoll** 2016-10-11 06:04 UTC
Labels: wontfix

**Comment by stefanheine** [comment] 2016-11-10 14:14
There is a good explanation in https://github.com/einfallstoll/express-ntlm/issues/20.
